In [1]:
# Import dependency
import pandas as pd

In [2]:
# Web page URL containing the pre-election polling table
url = 'https://www.realclearpolitics.com/epolls/other/trump_favorableunfavorable-5493.html#polls'

In [3]:
# Use Panda's read_html to parse the URL & display all of the tables
table = pd.read_html(url)
table

[                               Poll         Date   Sample  Favorable  \
 0                       RCP Average   8/9 - 8/31       --       42.3
 1        USA Today/SuffolkUSA Today  8/28 - 8/31  1000 RV       43.0
 2  Politico/Morning ConsultPolitico  8/28 - 8/30  1988 RV       42.0
 3            Economist/YouGovYouGov  8/23 - 8/25  1254 RV       44.0
 4      CNBC/Change Research (D)CNBC  8/21 - 8/23  2362 LV       42.0
 5                            CNNCNN  8/12 - 8/15   987 RV       43.0
 6          ABC News/Wash PostABC/WP  8/12 - 8/15   868 RV       41.0
 7     NBC News/Wall St. JrnlNBC/WSJ   8/9 - 8/12   900 RV       40.0
 8                  FOX NewsFOX News   8/9 - 8/12  1000 RV       43.0

    Unfavorable  Spread
 0         54.6   -12.3
 1         53.0   -10.0
 2         55.0   -13.0
 3         55.0   -11.0
 4         55.0   -13.0
 5         55.0   -12.0
 6         57.0   -16.0
 7         52.0   -12.0
 8         55.0   -12.0  ,
                        0
 0          42.3Favorable
 1  54.6Unfavorable +12.3,
                                  Poll         Date   Sample  Favorable  \
 0                         RCP Average   8/9 - 8/31       --       42.3
 1          USA Today/SuffolkUSA Today  8/28 - 8/31  1000 RV       43.0
 2    Politico/Morning ConsultPolitico  8/28 - 8/30  1988 RV       42.0
 3              Economist/YouGovYouGov  8/23 - 8/25  1254 RV       44.0
 4        CNBC/Change Research (D)CNBC  8/21 - 8/23  2362 LV       42.0
 ..                                ...          ...      ...        ...
 744     The Economist/YouGovEconomist  6/27 - 6/29   1000 A       30.0
 745     The Economist/YouGovEconomist  6/20 - 6/22   1000 A       32.0
 746                  MonmouthMonmouth  6/11 - 6/14   829 RV       18.0
 747     The Economist/YouGovEconomist  6/13 - 6/15   1000 A       26.0
 748              QuinnipiacQuinnipiac  5/19 - 5/26  1711 RV       20.0

      Unfavorable Spread
 0           54.6  -12.3
 1           53.0    -10
 2           55.0    -13
 3           55.0    -11
 4           55.0    -13
 ..           ...    ...
 744         60.0    -30
 745         60.0    -28
 746         57.0    -39
 747         60.0    -34
 748         69.0    -49

 [749 rows x 6 columns]]

In [4]:
# Assign the complete polling data table to the variable 'df' & display
df = table[2]
df

,Poll,Date,Sample,Favorable,Unfavorable,Spread
0,RCP Average,8/9 - 8/31,--,42.3,54.6,-12.3
1,USA Today/SuffolkUSA Today,8/28 - 8/31,1000 RV,43.0,53.0,-10
2,Politico/Morning ConsultPolitico,8/28 - 8/30,1988 RV,42.0,55.0,-13
3,Economist/YouGovYouGov,8/23 - 8/25,1254 RV,44.0,55.0,-11
4,CNBC/Change Research (D)CNBC,8/21 - 8/23,2362 LV,42.0,55.0,-13
...,...,...,...,...,...,...
744,The Economist/YouGovEconomist,6/27 - 6/29,1000 A,30.0,60.0,-30
745,The Economist/YouGovEconomist,6/20 - 6/22,1000 A,32.0,60.0,-28
746,MonmouthMonmouth,6/11 - 6/14,829 RV,18.0,57.0,-39
747,The Economist/YouGovEconomist,6/13 - 6/15,1000 A,26.0,60.0,-34
748,QuinnipiacQuinnipiac,5/19 - 5/26,1711 RV,20.0,69.0,-49

In [5]:
# Rename columns to match the column names of the other polling dataset
df2 = df.rename(columns={"Favorable":"Approve", "Unfavorable":"Disapprove"})

# Split the 'Sample' column into 'Sample' & 'Population' columns respectively
# Add the new column to the existing dataframe 
df2[['Sample','Population']] = df2.Sample.str.split(expand=True) 

# Show the dataframe
df2

,Poll,Date,Sample,Approve,Disapprove,Spread,Population
0,RCP Average,8/9 - 8/31,--,42.3,54.6,-12.3,None
1,USA Today/SuffolkUSA Today,8/28 - 8/31,1000,43.0,53.0,-10,RV
2,Politico/Morning ConsultPolitico,8/28 - 8/30,1988,42.0,55.0,-13,RV
3,Economist/YouGovYouGov,8/23 - 8/25,1254,44.0,55.0,-11,RV
4,CNBC/Change Research (D)CNBC,8/21 - 8/23,2362,42.0,55.0,-13,LV
...,...,...,...,...,...,...,...
744,The Economist/YouGovEconomist,6/27 - 6/29,1000,30.0,60.0,-30,A
745,The Economist/YouGovEconomist,6/20 - 6/22,1000,32.0,60.0,-28,A
746,MonmouthMonmouth,6/11 - 6/14,829,18.0,57.0,-39,RV
747,The Economist/YouGovEconomist,6/13 - 6/15,1000,26.0,60.0,-34,A
748,QuinnipiacQuinnipiac,5/19 - 5/26,1711,20.0,69.0,-49,RV

In [6]:
# Select the rows that contain polling info during the 2016 pre-election year
pre_election = df2.iloc[510:718]

# Display the selected rows to ensure the desired timeframe has been selected for
pre_election

,Poll,Date,Sample,Approve,Disapprove,Spread,Population
510,Economist/YouGovYouGov,12/24 - 12/27,1412,45.0,51.0,-6,RV
511,Rasmussen ReportsRasmussen,12/22 - 12/22,1000,51.0,47.0,+4,LV
512,Economist/YouGovYouGov,12/17 - 12/20,1185,46.0,50.0,-4,RV
513,Reuters/IpsosReuters,12/16 - 12/20,2065,52.0,48.0,+4,A
514,USA Today/SuffolkUSA Today,12/14 - 12/18,1000,41.0,46.0,-5,RV
...,...,...,...,...,...,...,...
713,QuinnipiacQuinnipiac,2/10 - 2/15,1342,37.0,57.0,-20,RV
714,PPP (D)PPP (D),2/2 - 2/3,1236,30.0,63.0,-33,RV
715,The Economist/YouGovEconomist,2/11 - 2/15,2000,38.0,57.0,-19,A
716,The Economist/YouGovEconomist,1/27 - 1/30,2000,36.0,58.0,-22,A
717,ABC News/Wash PostABC/WP,1/6 - 1/10,1000,35.0,62.0,-27,A

In [7]:
# Reset the index
pre_election_approval = pre_election.reset_index(drop=True)

# Split the 'Date' column into 'Start Date' & 'End Date' columns respectively, to match the other polling dataset
pre_election_approval[['Start_Date','End_Date']] = pre_election_approval.Date.str.split(" - ",expand=True)

# Preview the new columns in the dataframe
pre_election_approval.head()

,Poll,Date,Sample,Approve,Disapprove,Spread,Population,Start_Date,End_Date
0,Economist/YouGovYouGov,12/24 - 12/27,1412,45.0,51.0,-6,RV,12/24,12/27
1,Rasmussen ReportsRasmussen,12/22 - 12/22,1000,51.0,47.0,+4,LV,12/22,12/22
2,Economist/YouGovYouGov,12/17 - 12/20,1185,46.0,50.0,-4,RV,12/17,12/20
3,Reuters/IpsosReuters,12/16 - 12/20,2065,52.0,48.0,+4,A,12/16,12/20
4,USA Today/SuffolkUSA Today,12/14 - 12/18,1000,41.0,46.0,-5,RV,12/14,12/18

In [8]:
# Display the data types of all variables contained in the table
pre_election_approval.dtypes

Poll           object
Date           object
Sample         object
Approve       float64
Disapprove    float64
Spread         object
Population     object
Start_Date     object
End_Date       object
dtype: object

In [9]:
# Alter 'Start_Date' & 'End_Date' columns to be in datetime format & offset for correct year
pre_election_approval['Start_Date'] = pd.to_datetime(pre_election_approval['Start_Date'].str.strip(), format = '%m/%d')
pre_election_approval['Start_Date'] = pre_election_approval['Start_Date'] + pd.offsets.DateOffset(years=116)
pre_election_approval['End_Date'] = pd.to_datetime(pre_election_approval['End_Date'].str.strip(), format = '%m/%d')
pre_election_approval['End_Date'] = pre_election_approval['End_Date'] + pd.offsets.DateOffset(years=116)

In [10]:
# Drop duplicate rows in 'Start_Date' column
pre = pre_election_approval.drop_duplicates(subset=['Start_Date'])

In [11]:
# Set the index to Start_Date to serve as a primary key in the SQL database
pre_approval = pre.set_index('Start_Date')

# Reorder the columns to match the column order of the other polling dataframe
pre_approval = pre_approval[['End_Date', 'Poll', 'Approve', 'Disapprove', 'Spread', 'Sample', 'Population']]

# Drop any null value rows
pre_approval.dropna(inplace=True)

# Show cleaned-up dataframe
pre_approval

,End_Date,Poll,Approve,Disapprove,Spread,Sample,Population
Start_Date,,,,,,,
2016-12-24,2016-12-27,Economist/YouGovYouGov,45.0,51.0,-6,1412,RV
2016-12-22,2016-12-22,Rasmussen ReportsRasmussen,51.0,47.0,+4,1000,LV
2016-12-17,2016-12-20,Economist/YouGovYouGov,46.0,50.0,-4,1185,RV
2016-12-16,2016-12-20,Reuters/IpsosReuters,52.0,48.0,+4,2065,A
2016-12-14,2016-12-18,USA Today/SuffolkUSA Today,41.0,46.0,-5,1000,RV
...,...,...,...,...,...,...,...
2016-02-11,2016-02-15,Associated Press-GfKAP-GfK,32.0,58.0,-26,1033,A
2016-02-10,2016-02-15,QuinnipiacQuinnipiac,37.0,57.0,-20,1342,RV
2016-02-02,2016-02-03,PPP (D)PPP (D),30.0,63.0,-33,1236,RV
2016-01-27,2016-01-30,The Economist/YouGovEconomist,36.0,58.0,-22,2000,A
2016-01-06,2016-01-10,ABC News/Wash PostABC/WP,35.0,62.0,-27,1000,A

In [12]:
# Save to a new csv file to be imported into the SQL database
pre_approval.to_csv('Output_data/pre_election_approval.csv')